linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - errcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
